title: Geniospasm.com
author: Chris L.
email: chrijlowe@students.k12k.com
theme: minima
description: The official blog for all things Chris L! # this means to ignore newlines until "baseurl:"


# social links
github_username:  Boodle2003 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
